export const cardData = [
  {
    id: "big00",
    img: "/img/big22card/00-TheFool.jpg",
    title: "愚者",
    isntReserve: ["冒險", "純真", "自由", "開端", "勇往直前"],
    Reserve: ["魯莽", "粗心", "猶豫不決", "冒險過度", "不負責任"],
  },
  {
    id: "big01",
    img: "/img/big22card/01-TheMagician.jpg",
    title: "魔術師",
    isntReserve: ["熟練", "專注", "創造力", "行動力", "資源豐富"],
    Reserve: ["欺瞞", "操縱", "能力不足", "能量停滯", "投機取巧"],
  },
  {
    id: "big02",
    img: "/img/big22card/02-TheHighPriestess.jpg",
    title: "女教皇",
    isntReserve: ["直覺", "潛意識", "智慧", "神祕", "冷靜"],
    Reserve: ["膚淺", "缺乏遠見", "壓抑情緒", "流言蜚語", "直覺閉鎖"],
  },
  {
    id: "big03",
    img: "/img/big22card/03-TheEmpress.jpg",
    title: "皇后",
    isntReserve: ["豐收", "母性", "美感", "滋養", "生命力"],
    Reserve: ["懶散", "過度依賴", "缺乏創造力", "浪費", "情感停滯"],
  },
  {
    id: "big04",
    img: "/img/big22card/04-TheEmperor.jpg",
    title: "皇帝",
    isntReserve: ["權威", "穩定", "領導", "紀律", "結構"],
    Reserve: ["暴政", "缺乏自控", "僵化", "支配欲過強", "無能"],
  },
  {
    id: "big05",
    img: "/img/big22card/05-TheHierophant.jpg",
    title: "教皇",
    isntReserve: ["傳統", "體制", "教導", "精神指引", "歸屬感"],
    Reserve: ["反叛", "過時", "盲目遵循", "不道德", "僵化教條"],
  },
  {
    id: "big06",
    img: "/img/big22card/06-TheLovers.jpg",
    title: "戀人",
    isntReserve: ["選擇", "結合", "價值觀", "愛情", "和諧"],
    Reserve: ["不合", "失衡", "猶豫不決", "情感疏離", "錯誤決定"],
  },
  {
    id: "big07",
    img: "/img/big22card/07-TheChariot.jpg",
    title: "戰車",
    isntReserve: ["意志力", "勝利", "自律", "決心", "掌控"],
    Reserve: ["失控", "侵略性", "方向不明", "失敗", "壓力過大"],
  },
  {
    id: "big08",
    img: "/img/big22card/08-Strength.jpg",
    title: "力量",
    isntReserve: ["勇氣", "耐性", "內在力量", "柔中帶剛", "自信"],
    Reserve: ["軟弱", "自我懷疑", "情緒失控", "濫用權力", "退縮"],
  },
  {
    id: "big09",
    img: "/img/big22card/09-TheHermit.jpg",
    title: "隱者",
    isntReserve: ["冥想", "尋求真理", "內省", "孤獨", "引導"],
    Reserve: ["孤立", "偏執", "社會疏離", "粗心", "迷失方向"],
  },
  {
    id: "big10",
    img: "/img/big22card/10-WheelOfFortune.jpg",
    title: "命運之輪",
    isntReserve: ["轉機", "好運", "命運", "業力", "週期變化"],
    Reserve: ["厄運", "阻礙", "無法掌控", "負面連鎖", "時機不對"],
  },
  {
    id: "big11",
    img: "/img/big22card/11-Justice.jpg",
    title: "正義",
    isntReserve: ["公平", "真相", "法律", "因果", "責任"],
    Reserve: ["偏見", "不公正", "逃避責任", "不誠實", "嚴苛批判"],
  },
  {
    id: "big12",
    img: "/img/big22card/12-TheHangedMan.jpg",
    title: "吊人",
    isntReserve: ["犧牲", "換位思考", "等待", "奉獻", "新觀點"],
    Reserve: ["徒勞無功", "拖延", "頑固", "停滯不前", "缺乏自我"],
  },
  {
    id: "big13",
    img: "/img/big22card/13-Death.jpg",
    title: "死神",
    isntReserve: ["結束", "轉變", "淘汰", "新開端", "解脫"],
    Reserve: ["畏懼改變", "停滯", "沈溺過去", "僵局", "抗拒轉型"],
  },
  {
    id: "big14",
    img: "/img/big22card/14-Temperance.jpg",
    title: "節制",
    isntReserve: ["平衡", "調和", "耐性", "融合", "節制"],
    Reserve: ["失衡", "過度", "衝突", "缺乏目的", "混亂"],
  },
  {
    id: "big15",
    img: "/img/big22card/15-TheDevil.jpg",
    title: "惡魔",
    isntReserve: ["束縛", "慾望", "執著", "成癮", "物質主義"],
    Reserve: ["覺醒", "解脫", "重獲自由", "克服恐懼", "切斷聯繫"],
  },
  {
    id: "big16",
    img: "/img/big22card/16-TheTower.jpg",
    title: "高塔",
    isntReserve: ["劇變", "崩潰", "啟示", "災難", "解放"],
    Reserve: ["恐懼變動", "逃過一劫", "延遲崩壞", "自欺欺人", "受困"],
  },
  {
    id: "big17",
    img: "/img/big22card/17-TheStar.jpg",
    title: "星星",
    isntReserve: ["希望", "靈感", "療癒", "寧靜", "願景"],
    Reserve: ["絕望", "消沉", "缺乏信心", "空想", "運氣不佳"],
  },
  {
    id: "big18",
    img: "/img/big22card/18-TheMoon.jpg",
    title: "月亮",
    isntReserve: ["不安", "幻象", "直覺", "迷惘", "隱藏"],
    Reserve: ["真相大白", "克服焦慮", "解開誤解", "情緒穩定", "識破謊言"],
  },
  {
    id: "big19",
    img: "/img/big22card/19-TheSun.jpg",
    title: "太陽",
    isntReserve: ["成功", "快樂", "活力", "清晰", "自信"],
    Reserve: ["短暫挫折", "過度樂觀", "缺乏活力", "虛偽", "延遲成功"],
  },
  {
    id: "big20",
    img: "/img/big22card/20-Judgement.jpg",
    title: "審判",
    isntReserve: ["覺醒", "重生", "召喚", "抉擇", "因果報應"],
    Reserve: ["自我懷疑", "拒絕召喚", "猶豫", "錯過時機", "批判"],
  },
  {
    id: "big21",
    img: "/img/big22card/21-TheWorld.jpg",
    title: "世界",
    isntReserve: ["圓滿", "達成", "旅行", "整合", "成功"],
    Reserve: ["未完成", "延遲", "缺乏願景", "停滯", "虎頭蛇尾"],
  },
];
